<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $fillable = [
        'name',
        'birth_date',
        'gender',
        'civil_state',
        'nationality',
        'birthplace',
        'cpf',
        'rg',
        'issuing_agency',
        'issue_date',
        'voter_registration',
        'military_certificate',
        'mother_name',
        'father_name',
        'photo',
        'status',
        'ctps_number',
        'ctps_series',
        'ctps_state',
        'pis_pasep',
        'nit',
        'cnh',
        'cnh_category',
        'cnh_expiry',
        'professional_registration',
        'zip_code',
        'street',
        'number',
        'complement',
        'district',
        'city',
        'state',
        'phone',
        'mobile',
        'email',
        'emergency_contact',
        'emergency_phone',
        'bank',
        'agency',
        'account',
        'account_type',
        'pix_key',
        'role',
        'department',
        'contract_type',
        'admission_date',
        'termination_date',
        'salary',
        'work_schedule',
        'last_exam_date',
        'next_exam_date',
        'aso_result',
        'allergies',
        'blood_type',
        'accident_history',
        'education_level',
        'courses',
        'certifications',
        'experience'
    ];
}
